# -*- coding: utf-8 -*-
"""
游戏脚本工具（菜单 1「开启调试(Beta)」与菜单 7「植入中文文本处理插件」共用）。

能力：
  1. Ruby Marshal 4.8 读写（只支持 Scripts.rxdata 用到的
     Array / String / Fixnum / true/false / nil / 符号，足够应付该场景）。
  2. dump_scripts：把 Data/Scripts.rxdata 解包成 Data/Scripts/ 下的 rb 文件
     （仿社区通用的 Scripts.dump：[[ 分组名 ]] 建两级文件夹、"=====" 回到
     根目录、三位数字前缀保序，最后两份固定 999），
     并把 Scripts.rxdata 替换为「加载器」——运行时按文件名顺序加载
     全部 rb 文件，此后改 rb 文件即时生效；原文件备份为 ScriptsBackup.rxdata。
  3. enable_debug：四种注入方式（000_OpenDebug.rb / 删 $DEBUG 条件 /
     除虫喷雾触发 / F9 快捷键），可选调用模型分析，并输出修改报告。
     分析候选脚本、做少量额外修改，并输出修改说明 txt。
  4. inject_cn_plugin：植入「中文文本处理插件」（Settings.rb / Tools.rb），
     让游戏能正常绘制中文；字体使用随程序分发的萝莉体。
"""
import os
import re
import struct
import time
import zlib

import config
from logger import get_logger

log = get_logger("game_tools")

DEBUG_SCRIPT_NAME = "000_OpenDebug.rb"
DEBUG_SCRIPT_CODE = (
    "# -------------------------------------------------------------\n"
    "# Generated by the Pokemon translation tool: enable debug mode.\n"
    "# In Pokemon Essentials the debug menu (F9) is controlled by\n"
    "# $DEBUG; some older versions also check $TEST.\n"
    "# This file is loaded FIRST (000_ prefix).\n"
    "# -------------------------------------------------------------\n"
    "$DEBUG = true\n"
    "$TEST = true unless $TEST\n"
)

# ④ F9 hotkey script (~ prefix -> loaded last, can override Scene_Map)
F9_SCRIPT_NAME = "~zz_F9DebugHotkey.rb"
F9_SCRIPT_CODE = r"""# -------------------------------------------------------------
# Generated by the Pokemon translation tool: press F9 to open the
# debug menu. The ~ prefix makes it load last, so it can override
# the game's own Scene_Map#update.
# -------------------------------------------------------------
begin
  if defined?(Scene_Map) && defined?(Input) && defined?(Input::F9)
    class Scene_Map
      unless method_defined?(:__pkmn_tool_update)
        alias __pkmn_tool_update update
        def update(*args)
          __pkmn_tool_update(*args)
          if Input.trigger?(Input::F9)
            begin
              if defined?(pbDebugMenu)
                pbDebugMenu
              elsif defined?(pbDebugMenuCommands)
                pbDebugMenuCommands
              elsif defined?(pbDebug)
                pbDebug
              else
                pbMessage(_INTL("Debug menu entry not found."))
              end
            rescue Exception => e
              p e
            end
          end
        end
      end
    end
  end
rescue Exception
  # An injected script must never block the game from starting.
end
"""

# ③ 除虫喷雾里插入的询问块（放在 proc 开头 → 先于「还有步数」检查执行）
REPEL_INJECT_CODE = (
    "\n"
    "    # >>> Injected by the Pokemon translation tool: ask for debug mode\n"
    "    # >>> when the 100-step Repel is used.\n"
    "    if pbConfirmMessage(_INTL(\"Open debug？\"))\n"
    "      $DEBUG = true\n"
    "      $TEST = true\n"
    "      pbMessage(_INTL(\"Debug open。\"))\n"
    "    end\n"
    "    # <<< End of injection\n"
)

# 四种调试注入方式（菜单 1 下层供用户选择）
DEBUG_MODES = [
    {
        "key":  "startfile",
        "label": "① 直接添加 000_OpenDebug.rb",
        "desc": "在最先加载的脚本里直接把 $DEBUG / $TEST 设为 true，"
                "适用绝大多数 Pokémon Essentials 游戏"
                "用这一条即可（进游戏按 F9 打开调试菜单）。",
    },
    {
        "key":  "unlock",
        "label": "② 删掉 $DEBUG 条件（穿墙 / 调试菜单 / 宝可梦调试）",
        "desc": "用固定规则扫描全部脚本，把「只有 $DEBUG 为真才生效」的"
                "判断去掉：穿墙、调试菜单、宝可梦调试入口等都会变成"
                "无条件可用（不再依赖开关）。",
    },
    {
        "key":  "repel",
        "label": "③ 除虫喷雾触发（仅 100 步那款）",
        "desc": "把「是否开启调试」的询问注入到 100 步除虫喷雾的使用流程里，"
                "只有 :REPEL（100 步）会触发，200/250 步那两款不会；"
                "即使上一瓶喷雾还有步数残留也会先弹提示，选「是」即开启调试。",
    },
    {
        "key":  "f9",
        "label": "④ F9 一键打开调试菜单",
        "desc": "额外注入一个脚本：游戏中随时按 F9 直接打开调试菜单"
                "（依次尝试 pbDebugMenu / pbDebugMenuCommands / pbDebug），"
                "不依赖 $DEBUG 是否为真。",
    },
]
DEBUG_MODE_KEYS = [m["key"] for m in DEBUG_MODES]


def debug_mode_of(key):
    for m in DEBUG_MODES:
        if m["key"] == key:
            return m
    return DEBUG_MODES[0]

PLUGIN_SETTINGS_NAME = "~zz_ChineseTextSettings.rb"
PLUGIN_TOOLS_NAME = "~zz_ChineseTextRenderer.rb"

# ★ 加载顺序清单：解包时按 Scripts.rxdata 的原始顺序写出。
#   只按文件名排序是不够的 —— 文件夹里的编号会重新从 001 开始，
#   导致原本很靠后的脚本（如 005_Prism Ball Code）被提前加载，
#   而它 alias 的方法还没定义 → NameError（undefined method / 常量未初始化）。
LOAD_ORDER_FILE = "!load_order.txt"

# 加载器：按清单顺序 eval Data/Scripts 下全部 rb 文件
#   ① 000_*.rb（工具注入的开关类脚本）→ 最先
#   ② 清单里的文件（原始顺序）
#   ③ 清单外的文件（插件等）→ 最后，方便覆盖游戏自带函数
LOADER_CODE = r"""# Scripts loader —— generated by the Pokemon translation tool.
# Loads every .rb file under Data/Scripts in the ORIGINAL script order
# (see !load_order.txt); files not listed are loaded last.
begin
  dir = "Data/Scripts"
  order_file = dir + "/!load_order.txt"
  listed = []
  if File.file?(order_file)
    File.readlines(order_file).each do |line|
      rel = line.strip
      next if rel.empty? || rel.start_with?("#")
      f = File.join(dir, rel)
      listed.push(f) if File.file?(f)
    end
  end
  all = Dir.glob(dir + "/**/*.rb").sort
  rest = all - listed
  first = rest.select { |f| File.basename(f) =~ /^000_/ }
  last = rest - first
  (first + listed + last).each do |f|
    begin
      eval(File.read(f, mode: "rb").force_encoding("UTF-8"),
           TOPLEVEL_BINDING, f)
    rescue Exception => e
      p [f, e]
    end
  end
rescue Exception
  # The loader itself must never block the game from starting.
end
"""


# ================================================================
# Ruby Marshal 4.8 最小读写
# ================================================================
class MarshalError(Exception):
    pass


def _w_long(n):
    """Marshal 的 long 编码。"""
    if n == 0:
        return b"\x00"
    if 0 < n < 123:
        return bytes([n + 5])
    out = b""
    x = n
    while x:
        out += bytes([x & 0xFF])
        x >>= 8
    return bytes([len(out)]) + out


def _r_long(data, i):
    b = data[i]
    if b == 0:
        return 0, i + 1
    if b > 0:
        if b < 123 + 5 and b >= 5:      # 单字节正数：值 = b - 5
            return b - 5, i + 1
        # 多字节
        n = b
        val = int.from_bytes(data[i + 1:i + 1 + n], "little")
        return val, i + 1 + n
    # 负数（-124 < x < 0 → 251 + x）
    if b >= 0xFB - 123:
        return b - 0xFB, i + 1
    n = -b
    val = int.from_bytes(data[i + 1:i + 1 + n], "little", signed=True)
    return val, i + 1 + n


class _MReader:
    """只解析 Scripts.rxdata 会出现的类型。"""

    def __init__(self, data):
        self.data = data
        self.symbols = []
        self.i = 0

    def byte(self):
        b = self.data[self.i]
        self.i += 1
        return b

    def long_(self):
        v, self.i = _r_long(self.data, self.i)
        return v

    def parse(self):
        if self.data[self.i:self.i + 2] == b"\x04\x08":
            self.i += 2
        return self.object_()

    def object_(self):
        t = self.byte()
        c = chr(t)
        if c == "0":
            return None
        if c == "T":
            return True
        if c == "F":
            return False
        if c == "i":
            return self.long_()
        if c == ":":                      # symbol
            n = self.long_()
            raw = self.data[self.i:self.i + n]
            self.i += n
            sym = ":" + raw.decode("utf-8", "replace")
            self.symbols.append(sym)
            return sym
        if c == ";":                      # symlink
            idx = self.long_()
            return self.symbols[idx]
        if c == '"':                      # string（保留原始字节！）
            n = self.long_()
            raw = self.data[self.i:self.i + n]
            self.i += n
            return raw
        if c == "I":                      # ivar 扩展对象（字符串 + 编码等）
            obj = self.object_()
            cnt = self.long_()
            for _ in range(cnt):
                self.object_()            # key（:E 等）
                self.object_()            # value（T / 编码名符号）
            return obj
        if c == "[":                      # array
            n = self.long_()
            return [self.object_() for _ in range(n)]
        raise MarshalError(f"不支持的 Marshal 类型：{c!r}（偏移 {self.i - 1}）")


def _w_str(s):
    raw = s.encode("utf-8") if isinstance(s, str) else s
    # I + " + len + bytes + ivar(1) + :E + T(UTF-8)
    return (b'I"' + _w_long(len(raw)) + raw
            + b"\x06:\x06E" + b"T")


def marshal_dump_scripts(entries):
    """
    序列化 [[id, title, code], ...] 为 Marshal 字节
    （带 \\x04\\x08 头，字符串都标 UTF-8 编码，避免 Ruby 3.x 里
    纯 Marshal 字符串默认 US-ASCII 引发编码不兼容）。
    title / code 可以是 str（自动 UTF-8 编码）或 bytes（原样写入，
    用于已经 zlib 压缩过的脚本）。
    """
    out = b"\x04\x08["
    out += _w_long(len(entries))
    for id_, title, code in entries:
        out += b"[" + _w_long(3)
        out += b"i" + _w_long(int(id_))
        out += _w_str(str(title))
        out += _w_str(code)
        out += b"]"
    return out


def marshal_load_scripts(path):
    """
    读取 Scripts.rxdata，返回 [[id, title(str), code(str)], ...]。

    ★ rxdata 里第三项是 zlib 压缩的脚本源码，必须先解压再解码；
       少数未压缩的条目（如空脚本）原样按文本处理。
    """
    with open(path, "rb") as f:
        data = f.read()
    r = _MReader(data)
    obj = r.parse()
    if not isinstance(obj, list):
        raise MarshalError("Scripts.rxdata 顶层不是数组")
    out = []
    for e in obj:
        if not isinstance(e, list) or len(e) < 3:
            continue
        sid, title, code = e[0], e[1], e[2]
        if isinstance(sid, bytes):
            sid = sid.decode("utf-8", "replace")
        if isinstance(title, bytes):
            title = title.decode("utf-8", "replace")
        if isinstance(code, bytes):
            try:
                code = zlib.decompress(code)
            except zlib.error:
                pass                      # 未压缩的条目
            code = code.decode("utf-8", "replace")
        try:
            sid = int(sid)
        except (TypeError, ValueError):
            sid = 0
        out.append([sid, str(title), str(code)])
    return out


# ================================================================
# 提取脚本（仿社区 Scripts.dump）
# ================================================================
_ESCAPES = [("\\", "&bs;"), ("/", "&fs;"), (":", "&cn;"), ("*", "&as;"),
            ("?", "&qm;"), ('"', "&dq;"), ("<", "&lt;"), (">", "&gt;"),
            ("|", "&po;")]


def _title_to_filename(title):
    for ch, rep in _ESCAPES:
        title = title.replace(ch, rep)
    return title


def _digits(n, num=3):
    return str(n).zfill(num)


def _scripts_dir(game_dir):
    return os.path.join(game_dir, "Data", "Scripts")


def dump_scripts(game_dir, emit=None, force=False):
    """
    把 Data/Scripts.rxdata 解包为 Data/Scripts/*.rb，并写入「加载器」版
    Scripts.rxdata（原文件备份为 ScriptsBackup.rxdata）。

    ★ force=True：即使已解包过也重新提取（数据源用 ScriptsBackup.rxdata）。
      用于修复「解包后加载顺序被打乱」的游戏。

    返回 (提取的文件数, Scripts 目录, 已解包与否)。
    """
    def say(msg):
        if emit:
            emit(msg)

    rxdata = os.path.join(game_dir, "Data", "Scripts.rxdata")
    backup = os.path.join(game_dir, "Data", "ScriptsBackup.rxdata")
    if not os.path.exists(rxdata):
        raise FileNotFoundError(
            f"找不到 {rxdata} —— 请确认选择的是游戏根目录"
            f"（里面有 Data/Scripts.rxdata）")

    src = rxdata
    scripts = marshal_load_scripts(rxdata)
    if len(scripts) < 10:
        # ★ rxdata 只剩加载器一条 = 之前已经解包过；只要备份还在就按备份
        #   重新提取，否则「解包目录被删掉后」会卡在「已提取」的假状态里。
        if os.path.exists(backup):
            say("Scripts.rxdata 已是加载器版（脚本少于 10 条），"
                "检测到 ScriptsBackup.rxdata，自动按备份重新提取")
            src = backup
            scripts = marshal_load_scripts(backup)
        elif not force:
            say("Scripts.rxdata 看起来已经解包过（脚本少于 10 条），跳过提取")
            return 0, _scripts_dir(game_dir), True
    elif force:
        say("按备份 ScriptsBackup.rxdata 重新提取")

    path = _scripts_dir(game_dir)

    # 清空旧目录（只动 Data/Scripts，不碰别处）
    if os.path.isdir(path):
        import shutil
        shutil.rmtree(path)
    os.makedirs(path, exist_ok=True)

    folder_id = [1, 1]          # 最多两层文件夹
    file_id = 1
    level = 0
    folder_path = path
    folder_name = None
    written = 0

    order = []          # ★ 按原始顺序记录相对路径 → 写进加载顺序清单

    for i, (_sid, title, code) in enumerate(scripts):
        title = _title_to_filename(title).strip()
        code = code.replace("\r", "")
        if not title and not code:
            continue

        m = re.search(r"\[\[\s*(.+)\s*\]\]$", title)
        if m:                                  # 分组名 → 建文件夹
            section = (m.group(1) or "").strip() or "unnamed"
            folder_num = ("999" if i >= len(scripts) - 2
                          else _digits(folder_id[level]))
            folder_name = folder_num + "_" + section
            os.makedirs(os.path.join(folder_path, folder_name),
                        exist_ok=True)
            folder_id[level] += 1
            if level < len(folder_id) - 1:
                level += 1
                folder_id[level] = 1
                folder_path = os.path.join(folder_path, folder_name)
                folder_name = None
            file_id = 1
        elif title.startswith("====="):        # 回到根目录
            level = 0
            folder_path = path
            folder_name = None

        if not code:
            continue

        this_folder = folder_path
        if folder_name:
            this_folder = os.path.join(folder_path, folder_name)
        section = title.strip() or "unnamed"
        file_num = "999" if i >= len(scripts) - 1 else _digits(file_id)
        fname = file_num + "_" + section + ".rb"
        with open(os.path.join(this_folder, fname), "w",
                  encoding="utf-8", newline="") as f:
            f.write(code)
        order.append(os.path.relpath(os.path.join(this_folder, fname), path)
                     .replace("\\", "/"))
        file_id += 1
        written += 1

    # ★ 加载顺序清单：文件夹里的编号会从 001 重新开始，只按文件名排序会
    #   把原本靠后的脚本提前，导致 alias / 常量在定义之前被引用（NameError）
    with open(os.path.join(path, LOAD_ORDER_FILE), "w",
              encoding="utf-8", newline="") as f:
        f.write("# script load order (original Scripts.rxdata order)\n")
        f.write("\n".join(order) + "\n")

    # 备份原 rxdata
    backup = os.path.join(game_dir, "Data", "ScriptsBackup.rxdata")
    if not os.path.exists(backup) and src == rxdata:
        with open(rxdata, "rb") as fsrc, open(backup, "wb") as fdst:
            fdst.write(fsrc.read())

    # 用加载器替换 Scripts.rxdata
    install_loader(game_dir)

    say(f"[提取] 已解包 {written} 个脚本 → {path}")
    say(f"[提取] 已生成加载顺序清单 {LOAD_ORDER_FILE}"
        "（严格按原脚本顺序加载，避免 alias / 常量未定义）")
    say("[提取] Scripts.rxdata 已替换为加载器（原文件 → ScriptsBackup.rxdata），"
        "此后改动 rb 文件即时生效")
    log.info("dump_scripts：%s → %d 个脚本", game_dir, written)
    return written, path, False


def install_loader(game_dir):
    """把 Scripts.rxdata 替换成「加载器」版（先备份）。"""
    rxdata = os.path.join(game_dir, "Data", "Scripts.rxdata")
    backup = os.path.join(game_dir, "Data", "ScriptsBackup.rxdata")
    if not os.path.exists(backup):
        with open(rxdata, "rb") as fsrc, open(backup, "wb") as fdst:
            fdst.write(fsrc.read())
    entries = [[62054200, "Main", zlib.compress(LOADER_CODE.encode("utf-8"))]]
    data = marshal_dump_scripts(entries)
    tmp = rxdata + ".tmp"
    with open(tmp, "wb") as f:
        f.write(data)
    os.replace(tmp, rxdata)
    log.info("加载器已写入 %s（备份 %s）", rxdata, backup)


def is_dumped(game_dir):
    """是否已经解包（存在 Scripts 目录，或 rxdata 条目 < 10）。"""
    if os.path.isdir(_scripts_dir(game_dir)):
        return True
    rxdata = os.path.join(game_dir, "Data", "Scripts.rxdata")
    if not os.path.exists(rxdata):
        return False
    try:
        return len(marshal_load_scripts(rxdata)) < 10
    except Exception:
        return False


# ================================================================
# 开启调试：基础补丁 + 模型分析
# ================================================================
def _rb_files(scripts_dir):
    out = []
    for root, _dirs, files in os.walk(scripts_dir):
        for f in files:
            if f.lower().endswith(".rb"):
                out.append(os.path.join(root, f))
    return sorted(out)


def _rel(path, scripts_dir):
    return os.path.relpath(path, scripts_dir).replace("\\", "/")


def enable_debug_base(game_dir, emit=None):
    """写入 000_OpenDebug.rb。返回修改说明 dict（已存在则返回 None）。"""
    scripts_dir = _scripts_dir(game_dir)
    if not os.path.isdir(scripts_dir):
        raise FileNotFoundError(
            "还没有提取脚本：请先点上层「提取脚本为 rb 文件」")
    target = os.path.join(scripts_dir, DEBUG_SCRIPT_NAME)
    if os.path.exists(target):
        return None
    with open(target, "w", encoding="utf-8", newline="") as f:
        f.write(DEBUG_SCRIPT_CODE)
    log.info("调试补丁已写入 %s", target)
    return {
        "file": DEBUG_SCRIPT_NAME,
        "how": "新建文件（加载顺序第 1 位）",
        "change": "$DEBUG = true / $TEST = true（开启 Essentials 调试菜单）",
    }


def write_debug_report(game_dir, modifications, explanations, usages,
                       mode="startfile"):
    """写修改说明 txt，返回路径。"""
    report = os.path.join(game_dir, "调试修改报告.txt")
    info = debug_mode_of(mode)
    lines = [
        "# 开启调试模式 —— 修改报告",
        f"# 时间：{time.strftime('%Y-%m-%d %H:%M:%S')}",
        f"# 游戏：{game_dir}",
        f"# 注入方式：{info['label']}",
        "#",
        "# 调试原理：Pokémon Essentials 的调试功能由 $DEBUG / $TEST 控制，",
        "# 正常只有在 RPG Maker 编辑器里启动才会打开。",
        "# 本工具把脚本解包为 rb 文件并装上加载器，然后按你选的方式注入，",
        "# 改 rb 文件即时生效（无需重新编译 Scripts.rxdata）。",
        "=" * 60,
        "",
        "## 注入方式说明",
        f"· {info['desc']}",
        "",
        "## 修改列表",
    ]
    for mod in modifications:
        lines.append(f"· {mod['file']}（{mod['how']}）")
        lines.append(f"    {mod['change']}")
    if explanations:
        lines += ["", "## 模型分析说明"]
        lines += [f"· {e}" for e in explanations]
    if usages:
        lines += ["", "## 调试功能用法"]
        lines += [f"· {u}" for u in usages]
    else:
        lines += ["", "## 调试功能用法",
                  "· 进入游戏后按 F9 打开调试菜单（传送 / 改属性 / 加道具等）",
                  "· 按住 Ctrl 行走可以穿墙（调试模式下生效）",
                  "· 调试模式下事件可以右键跳过，对话按 Ctrl 快进"]
    lines += ["", "## 还原方法",
              "· 把 Data/ScriptsBackup.rxdata 改名回 Scripts.rxdata"
              "（先删除现在的 Scripts.rxdata），",
              "  再删除 Data/Scripts 文件夹即可完全还原。"]
    with open(report, "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(lines))
    return report


# ② 删条件：把「只有 $DEBUG 为真才生效」的判断去掉
_COND_PATS = [
    (re.compile(r"\bif\s+!\$DEBUG\s+&&\s+"), "if "),
    (re.compile(r"\bif\s+\$DEBUG\s+&&\s+"), "if "),
    (re.compile(r"\bif\s+\$DEBUG\s*\|\|\s*"), "if "),
    (re.compile(r"\bif\s+!\$DEBUG\b"), "if false"),
    (re.compile(r"\bif\s+\$DEBUG\b"), "if true"),
    (re.compile(r"\bunless\s+\$DEBUG\b"), "unless false"),
    (re.compile(r"\bif\s+!\$TEST\b"), "if false"),
    (re.compile(r"\bif\s+\$TEST\b"), "if true"),
]


def _strip_debug_conditions(game_dir):
    """
    ② 删掉 $DEBUG / $TEST 条件：穿墙、调试菜单、宝可梦调试等
    「只有调试模式才生效」的分支改成无条件执行。
    返回修改说明列表。
    """
    scripts_dir = _scripts_dir(game_dir)
    skip_prefix = (DEBUG_SCRIPT_NAME, "~zz_")
    mods = []
    for path in _rb_files(scripts_dir):
        name = os.path.basename(path)
        if name.startswith(skip_prefix):
            continue
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                text = f.read()
        except Exception:
            continue
        if "$DEBUG" not in text and "$TEST" not in text:
            continue
        new_text = text
        total = 0
        for pat, rep in _COND_PATS:
            new_text, n = pat.subn(rep, new_text)
            total += n
        # ★ 清理冗余：if false || X → if X；if true && X → if X；
        #   X && true / X || false → X；末尾的 if true 直接去掉
        for pat, rep in (
                (re.compile(r"\b(if|unless)\s+false\s*\|\|\s*"), r"\1 "),
                (re.compile(r"\b(if|unless)\s+true\s*&&\s*"), r"\1 "),
                (re.compile(r"\s*&&\s*true\b"), ""),
                (re.compile(r"\s*\|\|\s*false\b"), ""),
                (re.compile(r"\btrue\s*&&\s*"), ""),
                (re.compile(r"\bfalse\s*\|\|\s*"), ""),
                (re.compile(r"\s+if\s+true\s*$", re.MULTILINE), ""),
        ):
            new_text = pat.sub(rep, new_text)
        if not total or new_text == text:
            continue
        with open(path, "w", encoding="utf-8", newline="") as f:
            f.write(new_text)
        mods.append({
            "file": _rel(path, scripts_dir),
            "how": "条件改写",
            "change": f"把 {total} 处 $DEBUG / $TEST 判断改成无条件"
                      f"（if $DEBUG → if true，if !$DEBUG → if false）",
        })
        log.info("删条件：%s 共 %d 处", name, total)
    return mods


def _inject_repel(game_dir):
    """
    ③ 把「是否开启调试」注入 100 步除虫喷雾（:REPEL）。
    注入点选在 proc 最开头 → 先于「上一瓶还有步数」的检查执行，
    所以无论是否还有步数残留都会弹提示。
    """
    scripts_dir = _scripts_dir(game_dir)
    pats = [
        re.compile(r"[ \t]*ItemHandlers::UseInField\.add\(\s*:REPEL\s*,\s*"
                   r"(?:proc|lambda)\s*\{[^\n|]*\|[^\n]*"),
        re.compile(r"[ \t]*ItemHandlers::UseInField\.add\(\s*:REPEL\s*,"
                   r"[^\n]*\{\s*\|[^\n]*"),
        re.compile(r"[ \t]*ItemHandlers::UseInField\.add\(\s*:REPEL\s*,"
                   r"[^\n]*do\s*\|[^\n]*"),
    ]
    for path in _rb_files(scripts_dir):
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                text = f.read()
        except Exception:
            continue
        for pat in pats:
            m = pat.search(text)
            if not m:
                continue
            if REPEL_INJECT_CODE.strip()[:40] in text:
                return [{
                    "file": _rel(path, scripts_dir),
                    "how": "已存在（本次保留）",
                    "change": "除虫喷雾注入块已在文件中",
                }]
            new_text = (text[:m.end()] + "\n" + REPEL_INJECT_CODE
                        + text[m.end():])
            with open(path, "w", encoding="utf-8", newline="") as f:
                f.write(new_text)
            log.info("除虫喷雾注入：%s", _rel(path, scripts_dir))
            return [{
                "file": _rel(path, scripts_dir),
                "how": "注入到 :REPEL（100 步除虫喷雾）处理块开头",
                "change": "使用 100 步除虫喷雾时询问是否开启调试"
                          "（先于「还有步数」检查，残留步数也能触发）",
            }]
    return []


def _inject_f9(game_dir):
    """④ 写入 F9 打开调试菜单的脚本（~ 开头，最后加载）。"""
    scripts_dir = _scripts_dir(game_dir)
    target = os.path.join(scripts_dir, F9_SCRIPT_NAME)
    with open(target, "w", encoding="utf-8", newline="") as f:
        f.write(F9_SCRIPT_CODE)
    log.info("F9 脚本已写入 %s", target)
    return [{
        "file": F9_SCRIPT_NAME,
        "how": "新建文件（最后加载，覆盖 Scene_Map#update）",
        "change": "游戏中按 F9 直接打开调试菜单"
                  "（优先 pbDebugMenu，其次 pbDebugMenuCommands / pbDebug）",
    }]


def enable_debug(game_dir, mode="startfile", emit=None):
    """
    按选定方式开启调试（脚本需已提取）。
    返回 (modifications, report_path)。

    ★ 四种方式全部是「纯规则 / 纯文件写入」，一律不调用模型、不联网：
      ① startfile → 写 000_OpenDebug.rb
      ② unlock    → 用固定正则规则去掉 $DEBUG / $TEST 条件
      ③ repel     → 往 100 步除虫喷雾（:REPEL）处理块开头插询问
      ④ f9        → 写 ~zz_F9DebugHotkey.rb
    mode 取值见 DEBUG_MODES。
    """
    def say(msg):
        if emit:
            emit(msg)

    if mode not in DEBUG_MODE_KEYS:
        mode = "startfile"
    say(f"[调试] 注入方式：{debug_mode_of(mode)['label']}")

    modifications = []

    if mode == "startfile":
        base = enable_debug_base(game_dir, emit=emit)
        if base:
            modifications.append(base)
            say(f"[调试] 已写入 {DEBUG_SCRIPT_NAME}（$DEBUG = true）")
        else:
            modifications.append({
                "file": DEBUG_SCRIPT_NAME,
                "how": "已存在（本次保留）",
                "change": "$DEBUG = true / $TEST = true",
            })

    elif mode == "unlock":
        base = enable_debug_base(game_dir, emit=emit)
        if base:
            modifications.append(base)
            say(f"[调试] 已写入 {DEBUG_SCRIPT_NAME}（$DEBUG = true）")
        stripped = _strip_debug_conditions(game_dir)
        modifications.extend(stripped)
        if stripped:
            say(f"[调试] 已改写 {len(stripped)} 个文件里的 $DEBUG / $TEST 条件")
        else:
            say("[调试] 没找到需要改写的 $DEBUG / $TEST 条件"
                "（可能已经被改过，或该游戏靠 $DEBUG 以外的方式控制）")

    elif mode == "repel":
        injected = _inject_repel(game_dir)
        if injected:
            modifications.extend(injected)
            say(f"[调试] 已注入 {injected[0]['file']}（100 步除虫喷雾）")
        else:
            say("[调试] 没找到 :REPEL（100 步除虫喷雾）处理块；"
                "可换用方式①或④")

    elif mode == "f9":
        modifications.extend(_inject_f9(game_dir))
        say(f"[调试] 已写入 {F9_SCRIPT_NAME}（F9 打开调试菜单）")

    say("[调试] 该方式已完成")
    report = write_debug_report(game_dir, modifications, [], [], mode=mode)
    say(f"[调试] 修改说明已输出：{report}")
    return modifications, report


# ================================================================
# 还原（菜单 1「还原」按钮）
# ================================================================
def _plugin_copied_font(game_dir):
    """
    读插件 Settings 里的「# Copied font: xxx.ttf」标记，返回当初复制进
    Fonts 的字体文件名；没有标记（或没植入过）返回 None。
    """
    p = os.path.join(_scripts_dir(game_dir), PLUGIN_SETTINGS_NAME)
    if not os.path.isfile(p):
        return None
    try:
        with open(p, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                if line.startswith("# Copied font:"):
                    return line.split(":", 1)[1].strip() or None
    except Exception as e:
        log.warning("读取插件 Settings 失败：%s", e)
    return None


def _remove_copied_font(game_dir, font_name, say):
    """删掉当初复制进游戏 Fonts 的那份字体（游戏自带字体不会命中标记）。"""
    if not font_name:
        return False
    fp = os.path.join(game_dir, "Fonts", font_name)
    if not os.path.isfile(fp):
        return False
    try:
        os.remove(fp)
        say(f"[还原] 已删除 Fonts/{font_name}")
        return True
    except Exception as e:
        say(f"[还原] 删除 Fonts/{font_name} 失败：{e}")
        return False


def restore_injection(game_dir, emit=None):
    """
    还原「注入操作」：把工具改过的脚本恢复成解包时的样子。
    有备份 → 用 ScriptsBackup.rxdata 重新生成 Data/Scripts（最干净）；
    没备份 → 退而求其次，删掉工具注入的那几个文件。
    返回 dict。
    """
    def say(msg):
        if emit:
            emit(msg)

    backup = os.path.join(game_dir, "Data", "ScriptsBackup.rxdata")
    font_name = _plugin_copied_font(game_dir)      # ★ 重建目录前先记下字体名
    if os.path.exists(backup):
        n, path, _ = dump_scripts(game_dir, emit=emit, force=True)
        say(f"[还原] 已按备份重新生成脚本：{n} 个文件（注入内容已清除）")
        removed_font = _remove_copied_font(game_dir, font_name, say)
        return {"ok": True, "how": "backup", "files": n,
                "font_removed": removed_font}

    scripts_dir = _scripts_dir(game_dir)
    if not os.path.isdir(scripts_dir):
        raise FileNotFoundError("没有 Data/Scripts 目录，也没有备份，无从还原")

    removed = []
    for f in _rb_files(scripts_dir):
        base = os.path.basename(f)
        if base.startswith("000_") or base.startswith("~zz_"):
            try:
                os.remove(f)
                removed.append(_rel(f, scripts_dir))
            except Exception as e:
                log.warning("删除注入文件失败 %s：%s", f, e)
    if removed:
        say(f"[还原] 已删除工具注入的文件 {len(removed)} 个")
    else:
        say("[还原] 没找到工具注入的文件（可能已经还原过）")
    say("[还原] ⚠ 没有备份，被改写过的游戏脚本无法自动恢复，"
        "建议重新解包或重装游戏")
    removed_font = _remove_copied_font(game_dir, font_name, say)
    return {"ok": bool(removed), "how": "files", "files": removed,
            "font_removed": removed_font}


def restore_extraction(game_dir, emit=None):
    """
    还原「提取脚本」：删掉 Data/Scripts 目录，把备份改回 Scripts.rxdata，
    游戏回到未解包状态。
    """
    def say(msg):
        if emit:
            emit(msg)

    import shutil
    rxdata = os.path.join(game_dir, "Data", "Scripts.rxdata")
    backup = os.path.join(game_dir, "Data", "ScriptsBackup.rxdata")
    if not os.path.exists(backup):
        raise FileNotFoundError(
            f"找不到备份 {backup}，无法还原（原文件没有被替换过？）")

    scripts_dir = _scripts_dir(game_dir)
    if os.path.isdir(scripts_dir):
        shutil.rmtree(scripts_dir)
        say(f"[还原] 已删除 {scripts_dir}")

    with open(backup, "rb") as fsrc, open(rxdata, "wb") as fdst:
        fdst.write(fsrc.read())
    say(f"[还原] 已把备份恢复为 Scripts.rxdata（备份文件保留：{backup}）")
    say("[还原] 游戏已回到未解包状态；再点「提取脚本」可重新解包")
    log.info("还原提取：%s", game_dir)
    return {"ok": True}


# ================================================================
# 中文文本处理插件（Settings.rb / Tools.rb）
# ================================================================
# 译文渲染补丁：重写 getFormattedText / getLineBrokenText / pbDrawShadowText，
# 让游戏能逐字绘制中文（原版按西文断词，中文会显示成方块或错位）。
PLUGIN_TOOLS_CODE = r"""def getLineBrokenChunks(bitmap, value, width, dims, plain = false)
  x = 0
  y = 0
  ret = []
  if dims
    dims[0] = 0
    dims[1] = 0
  end
  return ret if !bitmap || bitmap.disposed? || width <= 0
  textmsg = value.clone
  color = Font.default_color
  textmsg.each_char do |ch|
    if ch == "\n"
      x = 0
      y += 32
      next
    end
    textSize = bitmap.text_size(ch)
    textwidth = textSize.width
    if x > 0 && x + textwidth > width && ch !~ /[[:punct:]]/
      x = 0
      y += 32
    end
    ret.push([ch, x, y, textwidth, 32, color])
    x += textwidth
    dims[0] = x if dims && dims[0] < x
  end
  dims[1] = y + 32 if dims
  ret
end

def getLineBrokenText(bitmap, value, width, dims)
  x = 0
  y = 0
  textheight = 0
  ret = []
  if dims
    dims[0] = 0
    dims[1] = 0
  end
  return ret if !bitmap || bitmap.disposed? || width <= 0

  textmsg = value.delete(" ").clone
  ret.push(["", 0, 0, 0, bitmap.text_size("中").height, 0, 0, 0, 0])
  textmsg.each_line do |line|
    length = line.scan(/./m).length
    line.each_char do |char|
      textSize = bitmap.text_size(char)
      textwidth = textSize.width
      if x > 0 && x + textwidth >= width - 2
        ret.push(["", x, y, 0, textheight, 0, 0, 0, 0])
        x = 0
        y += textheight.zero? ? bitmap.text_size("国").height : textheight
        textheight = 0
      end
      textheight = [textheight, textSize.height].max
      ret.push([char, x, y, textwidth, textheight, 0, 0, 0, length])
      x += textwidth
      dims[0] = x if dims && dims[0] < x
    end
    y += textheight if y > 0
  end
  dims[1] = y + textheight if dims
  ret
end


def ischinese?(char)
  char.ord >= 0x4e00 && char.ord <= 0x9fa5
end

def _MAPINTL(mapid, *arg)
  string = MessageTypes.getFromMapHash(mapid, arg[0])
  string = string.clone
  (1...arg.length).each do |i|
    string.gsub!(/\{#{i}\}/, arg[i].to_s)
  end
  string = string.gsub(/([\p{Han}\p{P}])\s+([\p{Han}\p{P}])/, '\1\2')
  return string
end

def getFormattedText(bitmap, xDst, yDst, widthDst, heightDst, text, lineheight = 32,
                     newlineBreaks = true, explicitBreaksOnly = false,
                     collapseAlignments = false)
  dummybitmap = nil
  if !bitmap || bitmap.disposed?   # allows function to be called with nil bitmap
    dummybitmap = Bitmap.new(1, 1)
    bitmap = dummybitmap
    return
  end
  if !bitmap || bitmap.disposed? || widthDst <= 0 || heightDst == 0 || text.length == 0
    return []
  end
  textchunks = []
  controls = []
  #  oldtext = text
  while text[FORMATREGEXP]
    textchunks.push($~.pre_match)
    if $~[3]
      controls.push([$~[2].downcase, $~[4], -1, $~[1] == "/"])
    else
      controls.push([$~[2].downcase, "", -1, $~[1] == "/"])
    end
    text = $~.post_match
  end
  if controls.length == 0
    ret = getFormattedTextFast(bitmap, xDst, yDst, widthDst, heightDst, text, lineheight,
                               newlineBreaks, explicitBreaksOnly)
    dummybitmap&.dispose
    return ret
  end
  x = y = 0
  characters = []
  charactersInternal = []
  textchunks.push(text)
  textchunks.each { |chunk| fmtReplaceEscapes(chunk) }
  textlen = 0
  controls.each_with_index do |control, i|
    textlen += textchunks[i].scan(/./m).length
    control[2] = textlen
  end
  text = textchunks.join
  textchars = text.scan(/./m)
  colorstack = []
  boldcount = 0
  italiccount = 0
  outlinecount = 0
  underlinecount = 0
  strikecount = 0
  rightalign = 0
  outline2count = 0
  opacitystack = []
  oldfont = bitmap.font.clone
  defaultfontname = bitmap.font.name
  defaultfontsize = bitmap.font.size
  fontsize = defaultfontsize
  fontnamestack = []
  fontsizestack = []
  defaultcolors = [oldfont.color.clone, nil]
  if defaultfontname.is_a?(Array)
    defaultfontname = defaultfontname.find { |i| Font.exist?(i) } || "Arial"
  elsif !Font.exist?(defaultfontname)
    defaultfontname = "Arial"
  end
  defaultfontname = defaultfontname.clone
  fontname = defaultfontname
  alignstack = []
  lastword = [0, 0] # position of last word
  hadspace = false
  hadnonspace = false
  havenl = false
  position = 0
  while position < textchars.length
    nextline = 0
    graphic = nil
    graphicX = 0
    graphicY = 4
    graphicWidth = nil
    graphicHeight = nil
    graphicRect = nil
    controls.length.times do |i|
      next if !controls[i] || controls[i][2] != position
      control = controls[i][0]
      param = controls[i][1]
      endtag = controls[i][3]
      case control
      when "c" then endtag ? colorstack.pop : colorstack.push([Color.new_from_rgb(param), nil])
      when "c2" then endtag ? colorstack.pop : colorstack.push([Color.new_from_rgb(param[0, 4]), Color.new_from_rgb(param[4, 4])])
      when "c3"
        if endtag
          colorstack.pop
        else
          param = param.split(",")
          oldColors = getLastParam(colorstack, defaultcolors)
          base = param[0].empty? ? oldColors[0] : Color.new_from_rgb(param[0])
          shadow = param[1].empty? ? oldColors[1] : Color.new_from_rgb(param[1])
          colorstack.push([base, shadow])
        end
      when "o" then endtag ? opacitystack.pop : opacitystack.push(param.sub(/\s+$/, "").to_i)
      when "b" then boldcount += endtag ? -1 : 1
      when "i" then italiccount += endtag ? -1 : 1
      when "u" then underlinecount += endtag ? -1 : 1
      when "s" then strikecount += endtag ? -1 : 1
      when "outln" then outlinecount += endtag ? -1 : 1
      when "outln2" then outline2count += endtag ? -1 : 1
      when "fs" then endtag ? fontsizestack.pop : fontsizestack.push(param.sub(/\s+$/, "").to_i)
      when "fn" then endtag ? fontnamestack.pop : fontnamestack.push(Font.exist?(param.sub(/\s+$/, "")) ? param.sub(/\s+$/, "") : "Arial")
      when "ar", "al", "ac"
        endtag ? alignstack.pop : alignstack.push(control[0] == "ar" ? 1 : control[0] == "al" ? 0 : 2)
        nextline = 1 if x > 0 && nextline == 0
      when "icon" then graphic = "Graphics/Icons/#{param.sub(/\s+$/, "")}" unless endtag
      when "img"
        unless endtag
          param = param.sub(/\s+$/, "").split("|")
          graphic = param[0]
          if param.length > 1
            graphicX, graphicY, graphicWidth, graphicHeight = param[1..4].map(&:to_i)
          end
        end
      when "br" then nextline += 1 unless endtag
      when "r"
        unless endtag
          x = 0
          rightalign = 1
          lastword = [characters.length, x]
        end
      end
      controls[i] = nil
    end
    bitmap.font.bold = (boldcount > 0)
    bitmap.font.italic = (italiccount > 0)
    if graphic
      if !graphicWidth
        tempgraphic = Bitmap.new(graphic)
        graphicWidth = tempgraphic.width
        graphicHeight = tempgraphic.height
        tempgraphic.dispose
      end
      width = graphicWidth   # +8  # No padding
      xStart = 0   # 4
      yStart = [(lineheight / 2) - (graphicHeight / 2), 0].max
      yStart += 4   # TEXT OFFSET
      graphicRect = Rect.new(graphicX, graphicY, graphicWidth, graphicHeight)
    else
      xStart = 0
      yStart = 0
      width = isWaitChar(textchars[position]) ? 0 : bitmap.text_size(textchars[position]).width
      width += 2 if width > 0 && outline2count > 0
    end
    if rightalign == 1 && nextline == 0
      alignment = 1
    else
      alignment = getLastParam(alignstack, 0)
    end
    nextline.times do
      havenl = true
      characters.push(["\n", x, (y * lineheight) + yDst, 0, lineheight, false, false, false,
                       defaultcolors[0], defaultcolors[1], false, false, "", 8, position, nil, 0])
      charactersInternal.push([alignment, y, 0])
      y += 1
      x = 0
      rightalign = 0
      lastword = [characters.length, x]
      hadspace = false
      hadnonspace = false
    end
    if textchars[position] == "\n"
      if newlineBreaks
        if nextline == 0
          havenl = true
          characters.push(["\n", x, (y * lineheight) + yDst, 0, lineheight, false, false, false,
                           defaultcolors[0], defaultcolors[1], false, false, "", 8, position, nil, 0])
          charactersInternal.push([alignment, y, 0])
          y += 1
          x = 0
        end
        rightalign = 0
        hadspace = true
        hadnonspace = false
        position += 1
        next
      else
        textchars[position] = " "
        if !graphic
          width = bitmap.text_size(textchars[position]).width
          width += 2 if width > 0 && outline2count > 0
        end
      end
    end
    if !ischinese?(textchars[position])
      isspace = (textchars[position][/\s/] || isWaitChar(textchars[position])) ? true : false
      if hadspace && !isspace
        # set last word to here
        lastword[0] = characters.length
        lastword[1] = x
        hadspace = false
        hadnonspace = true
      elsif isspace
        hadspace = true
      end
    else
      lastword[0] = characters.length
      lastword[1] = x
    end
    texty = (lineheight * y) + yDst + yStart - 2   # TEXT OFFSET
    colors = getLastColors(colorstack, opacitystack, defaultcolors)
    # Push character
    if heightDst < 0 || texty < yDst + heightDst
      havenl = true if !graphic && isWaitChar(textchars[position])
      extraspace = (!graphic && italiccount > 0) ? 2 + (width / 2) : 2
      characters.push([graphic || textchars[position],
                       x + xStart, texty, width + extraspace, lineheight,
                       graphic ? true : false,
                       (boldcount > 0), (italiccount > 0), colors[0], colors[1],
                       (underlinecount > 0), (strikecount > 0), fontname, fontsize,
                       position, graphicRect,
                       ((outlinecount > 0) ? 1 : 0) + ((outline2count > 0) ? 2 : 0)])
      charactersInternal.push([alignment, y, xStart, textchars[position], extraspace])
    end
    x += width
    if !explicitBreaksOnly && x + 2 > widthDst && lastword[1] != 0 &&
       (!hadnonspace || !hadspace)
      havenl = true
      characters.insert(lastword[0], ["\n", x, (y * lineheight) + yDst, 0, lineheight,
                                      false, false, false,
                                      defaultcolors[0], defaultcolors[1],
                                      false, false, "", 8, position, nil])
      charactersInternal.insert(lastword[0], [alignment, y, 0])
      lastword[0] += 1
      y += 1
      x = 0
      (lastword[0]...characters.length).each do |i|
        characters[i][2] += lineheight
        charactersInternal[i][1] += 1
        extraspace = (charactersInternal[i][4]) ? charactersInternal[i][4] : 0
        charwidth = characters[i][3] - extraspace
        characters[i][1] = x + charactersInternal[i][2]
        x += charwidth
      end
      lastword[1] = 0
    end
    position += 1 if !graphic
  end
  # This code looks at whether the text occupies exactly two lines when
  # displayed. If it does, it balances the length of each line.
  if havenl
    # Eliminate spaces before newlines and pause character
    firstspace = -1
    characters.length.times do |i|
      if characters[i][5] != false # If not a character
        firstspace = -1
      elsif (characters[i][0] == "\n" || isWaitChar(characters[i][0])) &&
            firstspace >= 0
        (firstspace...i).each do |j|
          characters[j] = nil
          charactersInternal[j] = nil
        end
        firstspace = -1
      elsif characters[i][0][/[ \r\t]/]
        firstspace = i if firstspace < 0
      else
        firstspace = -1
      end
    end
    if firstspace > 0
      (firstspace...characters.length).each do |j|
        characters[j] = nil
        charactersInternal[j] = nil
      end
    end
    characters.compact!
    charactersInternal.compact!
  end
  # Calculate Xs based on alignment
  # First, find all text runs with the same alignment on the same line
  totalwidth = 0
  widthblocks = []
  lastalign = 0
  lasty = 0
  runstart = 0
  characters.length.times do |i|
    c = characters[i]
    if i > 0 && (charactersInternal[i][0] != lastalign ||
       charactersInternal[i][1] != lasty)
      # Found end of run
      widthblocks.push([runstart, i, lastalign, totalwidth, lasty])
      runstart = i
      totalwidth = 0
    end
    lastalign = charactersInternal[i][0]
    lasty = charactersInternal[i][1]
    extraspace = (charactersInternal[i][4]) ? charactersInternal[i][4] : 0
    totalwidth += c[3] - extraspace
  end
  widthblocks.push([runstart, characters.length, lastalign, totalwidth, lasty])
  if collapseAlignments
    # Calculate the total width of each line
    totalLineWidths = []
    widthblocks.each do |block|
      y = block[4]
      totalLineWidths[y] = 0 if !totalLineWidths[y]
      if totalLineWidths[y] != 0
        # padding in case more than one line has different alignments
        totalLineWidths[y] += 16
      end
      totalLineWidths[y] += block[3]
    end
    # Calculate a new width for the next step
    widthDst = [widthDst, (totalLineWidths.compact.max || 0)].min
  end
  # Now, based on the text runs found, recalculate Xs
  widthblocks.each do |block|
    next if block[0] >= block[1]
    (block[0]...block[1]).each do |i|
      case block[2]
      when 1 then characters[i][1] = xDst + (widthDst - block[3] - 4) + characters[i][1]
      when 2 then characters[i][1] = xDst + ((widthDst / 2) - (block[3] / 2)) + characters[i][1]
      else        characters[i][1] = xDst + characters[i][1]
      end
    end
  end
  # Remove all characters with Y greater or equal to _yDst_+_heightDst_
  characters.delete_if { |ch| ch[2] >= yDst + heightDst } if heightDst >= 0
  bitmap.font = oldfont
  dummybitmap&.dispose
  return characters
end

def getFormattedTextFast(bitmap, xDst, yDst, widthDst, heightDst, text, lineheight,
                         newlineBreaks = true, explicitBreaksOnly = false)
  x = y = 0
  characters = []
  textchunks = []
  textchunks.push(text)
  text = textchunks.join
  textchars = text.scan(/./m)
  lastword = [0, 0] # position of last word
  hadspace = false
  hadnonspace = false
  bold = bitmap.font.bold
  italic = bitmap.font.italic
  colorclone = bitmap.font.color
  defaultfontname = bitmap.font.name
  if defaultfontname.is_a?(Array)
    defaultfontname = defaultfontname.find { |i| Font.exist?(i) } || "Arial"
  elsif !Font.exist?(defaultfontname)
    defaultfontname = "Arial"
  end
  defaultfontname = defaultfontname.clone
  havenl = false
  position = 0
  while position < textchars.length
    yStart = 0
    xStart = 0
    width = isWaitChar(textchars[position]) ? 0 : bitmap.text_size(textchars[position]).width
    if textchars[position] == "\n"
      if newlineBreaks   # treat newline as break
        havenl = true
        characters.push(["\n", x, (y * lineheight) + yDst, 0, lineheight, false, false,
                         false, colorclone, nil, false, false, "", 8, position, nil, 0])
        y += 1
        x = 0
        hadspace = true
        hadnonspace = false
        position += 1
        next
      else   # treat newline as space
        textchars[position] = " "
      end
    end
    if ischinese?(textchars[position])
      isspace = (textchars[position][/\s/] || isWaitChar(textchars[position])) ? true : false
      if hadspace && !isspace
        # set last word to here
        lastword[0] = characters.length
        lastword[1] = x
        hadspace = false
        hadnonspace = true
      elsif isspace
        hadspace = true
      end
    else
      lastword[0] = characters.length
      lastword[1] = x
    end
    texty = (lineheight * y) + yDst + yStart
    # Push character
    if heightDst < 0 || yStart < yDst + heightDst
      havenl = true if isWaitChar(textchars[position])
      characters.push([textchars[position],
                       x + xStart, texty, width + 2, lineheight,
                       false, bold, italic, colorclone, nil, false, false,
                       defaultfontname, bitmap.font.size, position, nil, 0])
    end
    x += width
    if !explicitBreaksOnly && x + 2 > widthDst && lastword[1] != 0 &&
       (!hadnonspace || !hadspace)
      havenl = true
      characters.insert(lastword[0], ["\n", x, (y * lineheight) + yDst, 0, lineheight,
                                      false, false, false, colorclone, nil, false, false, "", 8, position])
      lastword[0] += 1
      y += 1
      x = 0
      (lastword[0]...characters.length).each do |i|
        characters[i][2] += lineheight
        charwidth = characters[i][3] - 2
        characters[i][1] = x
        x += charwidth
      end
      lastword[1] = 0
    end
    position += 1
  end
  # Eliminate spaces before newlines and pause character
  if havenl
    firstspace = -1
    characters.length.times do |i|
      if characters[i][5] != false # If not a character
        firstspace = -1
      elsif (characters[i][0] == "\n" || isWaitChar(characters[i][0])) &&
            firstspace >= 0
        (firstspace...i).each do |j|
          characters[j] = nil
        end
        firstspace = -1
      elsif characters[i][0][/[ \r\t]/]
        firstspace = i if firstspace < 0
      else
        firstspace = -1
      end
    end
    if firstspace > 0
      (firstspace...characters.length).each do |j|
        characters[j] = nil
      end
    end
    characters.compact!
  end
  characters.each { |char| char[1] = xDst + char[1] }
  if heightDst >= 0
    characters.each_with_index do |char, i|
      characters[i] = nil if char[2] >= yDst + heightDst
    end
    characters.compact!
  end
  return characters
end

def pbDrawShadowText(bitmap, x, y, width, height, string, baseColor, shadowColor = nil, align = 0)
  return if !bitmap || !string
  width = (width < 0) ? bitmap.text_size(string).width + 1 : width
  height = (height < 0) ? bitmap.text_size(string).height + 1 : height
  y = y + Settings::Y_OFFSET_OF_TEXT - Settings::Y_OFFSET_OF_ORDER_CORRCETION
  if shadowColor && shadowColor.alpha > 0
    bitmap.font.color = shadowColor
    bitmap.draw_text(x + 2, y, width, height, string, align)
    bitmap.draw_text(x, y + 2, width, height, string, align)
    bitmap.draw_text(x + 2, y + 2, width, height, string, align)
  end
  if baseColor && baseColor.alpha > 0
    bitmap.font.color = baseColor
    bitmap.draw_text(x, y, width, height, string, align)
  end
end
"""


def _ttf_family_name(path):
    """
    从 TTF 的 name 表读字族名（优先 ID 16，其次 ID 1）。
    读不到返回 None。
    """
    try:
        with open(path, "rb") as f:
            data = f.read()
        if data[:4] not in (b"\x00\x01\x00\x00", b"true", b"OTTO"):
            return None
        num_tables = struct.unpack(">H", data[4:6])[0]
        name_off = None
        for i in range(num_tables):
            rec = data[12 + i * 16: 12 + i * 16 + 16]
            if rec[:4] == b"name":
                name_off = struct.unpack(">I", rec[8:12])[0]
                break
        if name_off is None:
            return None
        count = struct.unpack(">H", data[name_off + 2:name_off + 4])[0]
        str_off = name_off + struct.unpack(
            ">H", data[name_off + 4:name_off + 6])[0]
        found = {}
        for i in range(count):
            rec = data[name_off + 6 + i * 12: name_off + 6 + i * 12 + 12]
            platform, _enc, _lang, name_id = struct.unpack(
                ">HHHH", rec[:8])
            length, offset = struct.unpack(">HH", rec[8:12])
            if name_id in (1, 16) and name_id not in found:
                raw = data[str_off + offset: str_off + offset + length]
                try:
                    val = (raw.decode("utf-16-be") if platform in (0, 3)
                           else raw.decode("latin-1"))
                except Exception:
                    continue
                if val.strip():
                    found[name_id] = val.strip()
        return found.get(16) or found.get(1)
    except Exception as e:
        log.debug("读取字体族名失败：%s", e)
        return None


def font_family_name(path):
    """
    公开发布版：读取 TTF/OTF 的字族名（无法读取时返回 None）。
    插件植入前给用户预览字体信息用。
    """
    return _ttf_family_name(path)


def resolve_font(font_file=None):
    """
    确定植入时使用的字体，返回 (字体文件路径, 字族名, 输出提示行列表)。

    ★ 纯文件操作：不调用任何模型、不联网，只做「读 TTF 名字表 / 复制文件」。
    font_file 为空时用随程序分发的萝莉体。
    """
    notes = []
    path = font_file or config.FONT_FILE
    if not os.path.isfile(path):
        raise FileNotFoundError(f"字体文件不存在：{path}")
    family = _ttf_family_name(path) or config.FONT_NAME or "Lolita"
    notes.append(f"[插件] 字体：{os.path.basename(path)}（族名「{family}」）")
    return path, family, notes


def inject_cn_plugin(game_dir, emit=None, font_file=None):
    """
    植入中文文本处理插件（★ 纯文件写入，不调用模型）。

      1. 未解包过就先解包（会顺带装好加载器）；
      2. 写入 ~zz_ChineseTextSettings.rb / ~zz_ChineseTextRenderer.rb
         （~ 开头保证按文件名排序最后加载，能覆盖游戏自带函数）；
      3. 把选中的字体复制进游戏 Fonts 文件夹，字体名写进 Settings。

    ★ 只新增 / 覆盖这两个插件脚本与字体文件，不动游戏里其它任何脚本。
    font_file：用户自选的 TTF/OTF 路径；留空 = 内置萝莉体。
    返回 (植入的文件列表, 使用的字体族名)。
    """
    def say(msg):
        if emit:
            emit(msg)

    font_file, family, notes = resolve_font(font_file)
    for n in notes:
        say(n)

    # ★ 判据用「Data/Scripts 目录是否存在」：is_dumped() 对「rxdata 只剩
    #   加载器一条、目录却被删掉」的半吊子状态也会返回 True，会导致写到不存在的目录。
    if not os.path.isdir(_scripts_dir(game_dir)):
        say("[插件] 脚本尚未解包，先自动提取…")
        dump_scripts(game_dir, emit=emit)
    else:
        # 解包过但加载器可能被游戏还原，保险起见重写一次
        install_loader(game_dir)

    scripts_dir = _scripts_dir(game_dir)

    # 复制字体到游戏 Fonts 文件夹（mkxp-z 启动时会扫描该目录）
    fonts_dir = os.path.join(game_dir, "Fonts")
    os.makedirs(fonts_dir, exist_ok=True)
    font_dst = os.path.join(fonts_dir, os.path.basename(font_file))
    copied = os.path.abspath(font_dst) != os.path.abspath(font_file)
    if copied:
        with open(font_file, "rb") as fsrc, open(font_dst, "wb") as fdst:
            fdst.write(fsrc.read())
        say(f"[插件] 字体已复制：Fonts/{os.path.basename(font_file)}")

    settings_code = (
        "# Chinese text plugin - settings\n"
        "# Generated by the Pokemon translation tool.\n"
        # ★ 还原时靠这行判断字体是不是我们复制进去的（游戏自带的字体不能删）
        + (f"# Copied font: {os.path.basename(font_file)}\n" if copied
           else f"# Game font: {os.path.basename(font_file)}\n")
        + "module Settings\n"
        "\t# Vertical text offset (default 8; smaller value = lower text)\n"
        "\tY_OFFSET_OF_TEXT = 8\n\n"
        "\t# Command correction offset (default 8; smaller value = lower text)\n"
        "\tY_OFFSET_OF_ORDER_CORRCETION = 8\n\n"
        f"\t# Font family name (from {os.path.basename(font_file)})\n"
        f"\tGLOBAL_FONT_NAME = \"{family}\"\n"
        "end\n"
        "#=========================================================\n"
        "# Do not edit below this line.\n"
        "#=========================================================\n"
        "module MessageConfig\n"
        "  FONT_NAME                 = Settings::GLOBAL_FONT_NAME\n"
        "  SMALL_FONT_NAME           = Settings::GLOBAL_FONT_NAME\n"
        "  NARROW_FONT_NAME          = Settings::GLOBAL_FONT_NAME\n"
        "  FONT_Y_OFFSET             = Settings::Y_OFFSET_OF_TEXT\n"
        "  SMALL_FONT_Y_OFFSET       = Settings::Y_OFFSET_OF_TEXT\n"
        "  NARROW_FONT_Y_OFFSET      = Settings::Y_OFFSET_OF_TEXT\n"
        "end\n"
    )

    written = []
    for name, code in ((PLUGIN_SETTINGS_NAME, settings_code),
                       (PLUGIN_TOOLS_NAME, PLUGIN_TOOLS_CODE)):
        p = os.path.join(scripts_dir, name)
        with open(p, "w", encoding="utf-8", newline="") as f:
            f.write(code)
        written.append(name)
        say(f"[插件] 已写入 Scripts/{name}")

    say(f"[插件] 完成：游戏会通过加载器自动运行该插件，"
        f"中文将使用「{family}」逐字绘制")
    log.info("inject_cn_plugin：%s（字体 %s）", game_dir, family)
    return written, family


def restore_plugin(game_dir, emit=None):
    """
    还原「植入中文文本处理插件」：
      · 删掉 ~zz_ChineseTextSettings.rb / ~zz_ChineseTextRenderer.rb；
      · 当初复制进游戏 Fonts 的字体一并删掉（靠 Settings 里的
        「# Copied font: 」标记判断 —— 游戏自带的字体只会写
        「# Game font: 」，不会删）。
    只动这两个脚本与那一份字体，脚本解包状态与调试注入都不受影响。
    返回 {"removed": [...], "font": 字体文件名或 None, "found": bool}。
    """
    def say(msg):
        if emit:
            emit(msg)

    scripts_dir = _scripts_dir(game_dir)

    # ★ 先看标记：确认字体是我们复制进去的（游戏原有字体不能删）
    font_name = _plugin_copied_font(game_dir)

    removed, found = [], False
    for name in (PLUGIN_SETTINGS_NAME, PLUGIN_TOOLS_NAME):
        p = os.path.join(scripts_dir, name)
        if os.path.isfile(p):
            try:
                os.remove(p)
                removed.append(name)
                found = True
                say(f"[插件] 已删除 Scripts/{name}")
            except Exception as e:
                say(f"[插件] 删除 Scripts/{name} 失败：{e}")

    font_removed = _remove_copied_font(game_dir, font_name, say)
    if font_removed:
        removed.append(f"Fonts/{font_name}")

    if not found:
        say("[插件] 没有找到插件脚本（可能本来就没植入过）")
    else:
        say("[插件] 还原完成：插件脚本已删除"
            + ("，复制进去的字体也一并删除" if font_removed else ""))
    log.info("restore_plugin：%s → %s", game_dir, removed)
    return {"removed": removed, "font": font_name, "found": found}
